title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Join Our Discord: https://discord.gg/Es9FsVxH

logo: "assets/images/koth_logo.jpg"

favicon_ico: "assets/images/koth_logo.jpg"
